<a href="https://colab.research.google.com/github/wozzin/Natural_Language_Processing/blob/main/NLP_A_build_dtm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building a Document-Term Matrix from scratch


In [11]:
# install & import the libraries needed
!pip3 install pandas
!pip3 install scikit-learn
from typing import List
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
# A mini corpus to play with
CORPUS = [
    'this is the first document',
    'this is the second document',
    'and this is the third document',
    'is this the first document ?'
]

In [13]:
def tf(term: str, doc: str) -> int:
    ### TODO 1 ### 
    # count the frequency of term in doc. hint: str.count()
    tf = sum([
          term == word  # True (1) or False (0)
          for word in doc.split(" ")
    ])
    ##############
    return tf

In [21]:
def build_dtm(corpus: List[str]) -> pd.DataFrame:
    ### TODO 2 ###
    # build a vocabulary of the given corpus - use nested list comprehension, str.split(" "),  set,  and list
    vocab: List[str] = []
    words = [
             word
             for doc in corpus
             for word in doc.split(" ")
    ]
    vocab = list(set(words)) # 어휘(vocabulary)
    ##############

    ### TODO 3 ###
    # populate a dtm - get use of the tf function
    dtm: List[List[int]] = []
    dtm = [
           [tf(term, doc) for term in vocab]
           for doc in corpus
    ]
    print(dtm)
    ##############
    # return dtm as a pandas dataframe (for better visualization of the columns)
    dtm = pd.DataFrame(data=dtm, columns=vocab)
    return dtm

In [22]:
 # build a dtm from the corpus, and have a look at it
dtm = build_dtm(CORPUS)
print(dtm)

[[0, 1, 1, 1, 0, 0, 0, 1, 1], [0, 1, 1, 0, 1, 0, 0, 1, 1], [0, 1, 1, 0, 0, 1, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 1, 1]]
   ?  is  document  first  second  and  third  the  this
0  0   1         1      1       0    0      0    1     1
1  0   1         1      0       1    0      0    1     1
2  0   1         1      0       0    1      1    1     1
3  1   1         1      1       0    0      0    1     1


다음과 같은 결과가 나와야 합니다 (단어의 순서는 달라도 괜찮습니다):
```
   is  ?  first  and  document  this  the  second  third
0   2  0      1    0         1     1    1       0      0
1   2  0      0    0         1     1    1       1      0
2   2  0      0    1         1     1    1       0      1
3   2  1      1    0         1     1    1       0      0
```
(슬라이드에는 0또는 1로 카운트를 했지만, 튜토리얼에서는 그냥 카운트를 하겠습니다! (e.g. is가 두 개 포함되어 있다면 그냥 2로)

In [23]:
# this will print out the similarities of the documents to each other
sim_matrix = cosine_similarity(dtm.to_numpy(), dtm.to_numpy())
print(sim_matrix)

[[1.         0.8        0.73029674 0.91287093]
 [0.8        1.         0.73029674 0.73029674]
 [0.73029674 0.73029674 1.         0.66666667]
 [0.91287093 0.73029674 0.66666667 1.        ]]
